### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by ralftar** [vendanor/preview-pull-request#224] opened 2023-01-31 13:38 UTC
Lots of these.

**Comment by ralftar** [comment] 2023-04-11 10:21
@thomastvedt do you know where these come from? Was unable to find them in the source code at first glance.

**Comment by jonaski** [comment] 2023-04-12 09:25
set-output is not in our code. We have updated all packages.

**Comment by thomastvedt** [comment] 2023-04-12 10:39
I think we can close this @ralftar , we could not reproduce the warning message after bumping packages. v3.11.

**Closed** 2023-04-12 11:29 UTC
